apiVersion: v1
entries:
  neo4j-community:
  - apiVersion: v1
    appVersion: 3.5.17
    created: "2020-05-05T08:44:07.695246511Z"
    description: Neo4j is the world's leading graph database
    digest: bcbd5cbdfc691064d57ecd5ca824ba56873322615cc9c6d6520d7a54fd3cf655
    home: https://www.neo4j.com
    icon: http://info.neo4j.com/rs/773-GON-065/images/neo4j_logo.png
    maintainers:
    - email: sovrevage@gmail.com
      name: StianOvrevage
    name: neo4j-community
    sources:
    - https://github.com/neo4j/neo4j
    - https://github.com/neo4j/docker-neo4j
    - https://github.com/mneedham/k8s-kubectl
    - https://github.com/equinor/helm-charts/charts/neo4j-community
    urls:
    - neo4j-community-1.0.3.tgz
    version: 1.0.3
  - apiVersion: v1
    appVersion: 3.5.17
    created: "2020-05-05T08:44:07.694708311Z"
    description: Neo4j is the world's leading graph database
    digest: 1f9a6f47cdf98cbe54081f581bd607acab2549ea6531e9c17f46fbedce8f2547
    home: https://www.neo4j.com
    icon: http://info.neo4j.com/rs/773-GON-065/images/neo4j_logo.png
    maintainers:
    - email: sovrevage@gmail.com
      name: StianOvrevage
    name: neo4j-community
    sources:
    - https://github.com/neo4j/neo4j
    - https://github.com/neo4j/docker-neo4j
    - https://github.com/mneedham/k8s-kubectl
    - https://github.com/equinor/helm-charts/charts/neo4j-community
    urls:
    - neo4j-community-1.0.2.tgz
    version: 1.0.2
generated: "2020-05-05T08:44:07.69380161Z"
