name: Fetch and lint

on: [push, pull_request]

jobs:
  fetch:
    name: Fetch
    runs-on: ubuntu-latest
    env:
      GITHUB_WORKSPACE: /charts
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Download chart-testing and dependencies
      run: |
        pwd

        echo $GITHUB_WORKSPACE

        sudo apt-get update
        
        sudo apt-get install -y curl git python3-pip

        sudo pip3 install setuptools

        sudo pip3 install --user yamllint yamale

        curl -fsSL https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | sudo bash

        sudo curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl

        curl -L https://github.com/helm/chart-testing/releases/download/v3.0.0-rc.1/chart-testing_3.0.0-rc.1_linux_amd64.tar.gz | sudo tar xz
    - name: Lint chart
      run: |
        ./ct lint --chart-dirs charts/ --all --debug --remote origin --target-branch master --lint-conf ./etc/lintconf.yaml --chart-yaml-schema ./etc/chart_schema.yaml
    - name: Package charts and create new index
      run: |
        ls -d ./charts/*/ | xargs helm package --destination ./charts

        helm repo index ./charts

